version: '3'

services: 

  nginx-node:
    build:
      context: nginx
    container_name: nginx-node
    networks:
      - node-network
    tty: true
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
       - "8000:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/db:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      
