version: '3'

services: 

  nginx-node:
    build:
      context: nginx
    container_name: nginx-node
    entrypoint: dockerize -wait http://app:3000 -timeout 60s /docker-entrypoint.sh
    command: [nginx, '-g', 'daemon off;']
    networks:
      - node-network
    tty: true
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
       - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/db:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      
